package opencode

import (
	"bytes"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/kareemaly/agentstatus"
	"github.com/kareemaly/agentstatus/internal/configfile"
)

const pluginTemplate = `// @managed-by-agentstatus: opencode
// Auto-generated by agentstatus. Edit agentstatus config and re-install instead.
// Remove via UninstallHooks() — direct deletion is safe too.

export default {
  id: "agentstatus.opencode",
  server: async (_input) => ({
    event: async ({ event }) => {
      try {
        const props = event.properties as any
        const sessionID = props?.sessionID ?? ""
        const parentSessionID = props?.info?.parentID ?? ""
        await fetch("{{.Endpoint}}/opencode", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            hook_event_name: event.type,
            session_id: sessionID,
            parent_session_id: parentSessionID,
            payload: props,
          }),
        })
      } catch {}
    },
    "tool.execute.before": async (inp, _out) => {
      try {
        await fetch("{{.Endpoint}}/opencode", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            hook_event_name: "tool.execute.before",
            session_id: inp.sessionID,
            parent_session_id: "",
            payload: { tool: inp.tool, callID: inp.callID },
          }),
        })
      } catch {}
    },
    "tool.execute.after": async (inp, _out) => {
      try {
        await fetch("{{.Endpoint}}/opencode", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            hook_event_name: "tool.execute.after",
            session_id: inp.sessionID,
            parent_session_id: "",
            payload: { tool: inp.tool, callID: inp.callID },
          }),
        })
      } catch {}
    },
  }),
}
`

const managedMarker = "@managed-by-agentstatus: opencode"

// resolvePath returns (path, "") for the install target.
//
// Resolution order:
//  1. cfg.Project (absolute) → <Project>/.opencode/plugins/agentstatus.ts (project-local)
//  2. cfg.ConfigRoot (tests) → <ConfigRoot>/.config/opencode/plugins/agentstatus.ts
//     (ConfigRoot stands in for HOME, matching the Claude/Codex pattern)
//  3. Default: <$XDG_CONFIG_HOME or $HOME/.config>/opencode/plugins/agentstatus.ts
//     (user-level; matches OpenCode's documented global plugin location)
//
// OpenCode accepts both `plugin/` (singular) and `plugins/` (plural) as the
// subdirectory name. We write to `plugins/` to match the official docs and
// peon-ping's convention.
func resolvePath(cfg agentstatus.InstallConfig) (string, string) {
	if cfg.Project != "" {
		return filepath.Join(cfg.Project, ".opencode", "plugins", "agentstatus.ts"), ""
	}
	if cfg.ConfigRoot != "" {
		return filepath.Join(cfg.ConfigRoot, ".config", "opencode", "plugins", "agentstatus.ts"), ""
	}
	return filepath.Join(userConfigDir(), "opencode", "plugins", "agentstatus.ts"), ""
}

// userConfigDir resolves the XDG-compliant user config base directory,
// respecting $XDG_CONFIG_HOME if set. Falls back to $HOME/.config on macOS
// and Linux. This intentionally does NOT use os.UserConfigDir() because that
// returns ~/Library/Application Support on macOS, which is not where OpenCode
// looks for plugins.
func userConfigDir() string {
	if xdg := os.Getenv("XDG_CONFIG_HOME"); xdg != "" {
		return xdg
	}
	home, err := os.UserHomeDir()
	if err != nil || home == "" {
		return ""
	}
	return filepath.Join(home, ".config")
}

func installHooks(cfg agentstatus.InstallConfig) (agentstatus.InstallResult, error) {
	path, _ := resolvePath(cfg)

	unlock, err := configfile.Lock(path)
	if err != nil {
		return agentstatus.InstallResult{
			Agent:  agentstatus.OpenCode,
			Reason: fmt.Sprintf("failed to acquire lock: %v", err),
		}, fmt.Errorf("opencode install lock: %w", err)
	}
	defer unlock()

	// Check if file exists and is managed
	if data, err := os.ReadFile(path); err == nil {
		if bytes.Contains(data, []byte(managedMarker)) {
			// Check if endpoint matches
			if endpointMatches(string(data), cfg.Endpoint) {
				return agentstatus.InstallResult{
					Agent:     agentstatus.OpenCode,
					Installed: true,
					Path:      path,
				}, nil
			}
			// Endpoint differs; regenerate
		} else {
			// File exists but not managed
			return agentstatus.InstallResult{
				Agent:  agentstatus.OpenCode,
				Reason: fmt.Sprintf("plugin file exists but is not agentstatus-managed; refusing to overwrite: %s", path),
			}, fmt.Errorf("opencode install: non-managed file exists")
		}
	}

	// Create parent directory
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return agentstatus.InstallResult{
			Agent:  agentstatus.OpenCode,
			Reason: fmt.Sprintf("failed to create directory: %v", err),
		}, fmt.Errorf("opencode mkdir: %w", err)
	}

	// Generate plugin from template
	tmpl, err := template.New("plugin").Parse(pluginTemplate)
	if err != nil {
		return agentstatus.InstallResult{
			Agent:  agentstatus.OpenCode,
			Reason: fmt.Sprintf("template parse error: %v", err),
		}, fmt.Errorf("opencode template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, map[string]string{"Endpoint": cfg.Endpoint}); err != nil {
		return agentstatus.InstallResult{
			Agent:  agentstatus.OpenCode,
			Reason: fmt.Sprintf("template execute error: %v", err),
		}, fmt.Errorf("opencode template execute: %w", err)
	}

	// Backup existing file if present
	_, _ = configfile.Backup(path)

	// Write file atomically
	if err := configfile.Write(path, buf.Bytes()); err != nil {
		return agentstatus.InstallResult{
			Agent:  agentstatus.OpenCode,
			Reason: fmt.Sprintf("write error: %v", err),
		}, fmt.Errorf("opencode write: %w", err)
	}

	// Warn if OPENCODE_PURE is set
	if os.Getenv("OPENCODE_PURE") != "" {
		slog.Default().Warn("OPENCODE_PURE=1 detected — OpenCode will not load external plugins, including this one. Unset to use agentstatus.")
	}

	return agentstatus.InstallResult{
		Agent:     agentstatus.OpenCode,
		Installed: true,
		Path:      path,
	}, nil
}

func uninstallHooks(cfg agentstatus.InstallConfig) (agentstatus.InstallResult, error) {
	path, _ := resolvePath(cfg)

	unlock, err := configfile.Lock(path)
	if err != nil {
		return agentstatus.InstallResult{
			Agent:  agentstatus.OpenCode,
			Reason: fmt.Sprintf("failed to acquire lock: %v", err),
		}, fmt.Errorf("opencode uninstall lock: %w", err)
	}
	defer unlock()

	// Check if file exists
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return agentstatus.InstallResult{
				Agent:   agentstatus.OpenCode,
				Skipped: true,
				Reason:  "plugin file not found",
				Path:    path,
			}, nil
		}
		return agentstatus.InstallResult{
			Agent:  agentstatus.OpenCode,
			Reason: fmt.Sprintf("read error: %v", err),
		}, fmt.Errorf("opencode uninstall read: %w", err)
	}

	// Check if file is managed
	if !bytes.Contains(data, []byte(managedMarker)) {
		return agentstatus.InstallResult{
			Agent:  agentstatus.OpenCode,
			Reason: fmt.Sprintf("plugin file at %s is not agentstatus-managed; refusing to remove", path),
		}, fmt.Errorf("opencode uninstall: non-managed file")
	}

	// Remove file
	if err := os.Remove(path); err != nil {
		return agentstatus.InstallResult{
			Agent:  agentstatus.OpenCode,
			Reason: fmt.Sprintf("remove error: %v", err),
		}, fmt.Errorf("opencode uninstall remove: %w", err)
	}

	return agentstatus.InstallResult{
		Agent: agentstatus.OpenCode,
		Path:  path,
	}, nil
}

func endpointMatches(content, endpoint string) bool {
	expected := endpoint + "/opencode"
	return strings.Contains(content, expected)
}
